version: "3.8"
services:
  db:
    image: postgres:15
    container_name: foam_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: foam_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: foam_web
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:password@db:5432/foam_db
    depends_on:
      - db
    volumes:
      - .:/foam

volumes:
  pgdata:
