version: "3.8"

services:
  db:
    image: postgres:15
    container_name: foam_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: foam_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: foam_redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: foam_web
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:password@db:5432/foam_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/app

  celery_worker:
    build: .
    container_name: foam_celery_worker
    command: celery -A src.worker.celery_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:password@db:5432/foam_db
      - REDIS_URL=redis://redis:6379/0

  celery_beat:
    build: .
    container_name: foam_celery_beat
    command: celery -A src.worker.celery_app beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:password@db:5432/foam_db
      - REDIS_URL=redis://redis:6379/0

volumes:
  pgdata:
  redisdata:
