"""added new models

Revision ID: 948f44bd7abf
Revises: 970ab7cab910
Create Date: 2025-09-24 09:12:20.806182

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "948f44bd7abf"
down_revision: Union[str, Sequence[str], None] = "970ab7cab910"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("event_name", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("event_description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(op.f("ix_events_event_id"), "events", ["event_id"], unique=False)
    op.create_index(op.f("ix_events_user_id"), "events", ["user_id"], unique=False)
    op.create_table(
        "messages",
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("message_body", sa.Text(), nullable=False),
        sa.Column("file_url", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.event_id"],
        ),
        sa.PrimaryKeyConstraint("message_id"),
    )
    op.create_index(
        op.f("ix_messages_message_id"), "messages", ["message_id"], unique=False
    )
    op.create_table(
        "recipients",
        sa.Column("recipients_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("recipients_name", sa.String(length=100), nullable=False),
        sa.Column("recipients_email", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.event_id"],
        ),
        sa.PrimaryKeyConstraint("recipients_id"),
    )
    op.create_index(
        op.f("ix_recipients_recipients_email"),
        "recipients",
        ["recipients_email"],
        unique=True,
    )
    op.create_index(
        op.f("ix_recipients_recipients_id"),
        "recipients",
        ["recipients_id"],
        unique=False,
    )
    op.create_table(
        "messages_scheduler",
        sa.Column("messages_scheduler_id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("frequency_type", sa.String(length=50), nullable=False),
        sa.Column("start_date", sa.DateTime(), nullable=False),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.message_id"],
        ),
        sa.PrimaryKeyConstraint("messages_scheduler_id"),
    )
    op.create_index(
        op.f("ix_messages_scheduler_messages_scheduler_id"),
        "messages_scheduler",
        ["messages_scheduler_id"],
        unique=False,
    )
    op.create_table(
        "schedule_times",
        sa.Column("schedule_times_id", sa.UUID(), nullable=False),
        sa.Column("message_scheduler_id", sa.UUID(), nullable=False),
        sa.Column("send_time", sa.Time(), nullable=False),
        sa.Column("day_of_week", sa.Integer(), nullable=True),
        sa.Column("week_of_month", sa.Integer(), nullable=True),
        sa.Column("day_of_month", sa.Integer(), nullable=True),
        sa.Column("month_of_year", sa.Integer(), nullable=True),
        sa.Column("specific_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["message_scheduler_id"],
            ["messages_scheduler.messages_scheduler_id"],
        ),
        sa.PrimaryKeyConstraint("schedule_times_id"),
    )
    op.create_index(
        op.f("ix_schedule_times_schedule_times_id"),
        "schedule_times",
        ["schedule_times_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_schedule_times_schedule_times_id"), table_name="schedule_times"
    )
    op.drop_table("schedule_times")
    op.drop_index(
        op.f("ix_messages_scheduler_messages_scheduler_id"),
        table_name="messages_scheduler",
    )
    op.drop_table("messages_scheduler")
    op.drop_index(op.f("ix_recipients_recipients_id"), table_name="recipients")
    op.drop_index(op.f("ix_recipients_recipients_email"), table_name="recipients")
    op.drop_table("recipients")
    op.drop_index(op.f("ix_messages_message_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_events_user_id"), table_name="events")
    op.drop_index(op.f("ix_events_event_id"), table_name="events")
    op.drop_table("events")
    # ### end Alembic commands ###
