"""added new models

Revision ID: 970ab7cab910
Revises: a9a8438b0f58
Create Date: 2025-09-24 08:47:29.609439

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "970ab7cab910"
down_revision: Union[str, Sequence[str], None] = "a9a8438b0f58"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("user_id", sa.UUID(), nullable=False))
    op.add_column(
        "users",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
    )
    op.alter_column(
        "users",
        "email",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.create_index(op.f("ix_users_user_id"), "users", ["user_id"], unique=False)
    op.drop_column("users", "id")
    op.create_primary_key("users", ["user_id"])
    op.drop_column("users", "full_name")
    op.drop_column("users", "occupation")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "occupation", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "full_name", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "users", sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False)
    )
    op.create_primary_key("users", ["id"])
    op.drop_index(op.f("ix_users_user_id"), table_name="users")
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.alter_column(
        "users",
        "email",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.drop_column("users", "updated_at")
    op.drop_column("users", "created_at")
    op.drop_constraint("users_pkey", "users", type_="primary")
    op.drop_column("users", "user_id")
    # ### end Alembic commands ###
